name: Test deployment

on:
  pull_request:
    branches: [master]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          cache: npm
      - name: Test build
        working-directory: website
        run: |
          npm install --global yarn
          yarn install
