name: Test deployment

on:
  pull_request:
    branches: [master]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Test build
        working-directory: website
        run: |
          npm install --global yarn
          yarn install --immutable --immutable-cache --check-cache
          yarn build
